name: 'Upload blocklet'
description: 'Upload blocklet to blocklet registry'
inputs:
  endpoint:
    description: 'Endpoint of blocklet registry'
    required: true
  access-token:
    description: 'Access token of blocklet registry'
    required: false
  developer-sk:
    description: 'Developer-sk of blocklet registry'
    required: false
  file-path:
    description: 'blocklet.json path'
    default: .blocklet/release/blocklet.json
    required: false
  slack-webhook:
    description: 'Webhook of slack'
    required: false
  working-directory:
    description: 'Working directory'
    default: ./
    required: false
  skip:
    description: 'Skip action'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
